### ISSUE TITLE
python 2 code hit when running in python 3

### ISSUE THREAD

**Issue by drevicko** [gsi-upm/senpy#9]
Collecting pattern
  Using cached pattern-2.6.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-losdgxhb/pattern/setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'

**Comment by drevicko** [comment]
Weird thing is that it's also using pip from a different user. This is likely a local problem but I thought the python-2 probelm may need adressing.

Here's the rest of the output that generated the exception. The folder ianwoo pip reports ins't in the home folder of the user running senpy, and pip 8.1.2 is the version current in ianwoo's anaconda install (this user has pip 9.x).

INFO:senpy.extensions:Installing requirements: ['nltk>=3.0.5', 'numpy>=1.8.2', 'scipy>=0.14.0', 'scikit-learn>=0.14.1', 'lxml>=3.4.2', 'pandas', 'senpy', 'pattern', 'collections', 'sklearn', 'math', 'itertools']
Requirement already satisfied (use --upgrade to upgrade): nltk>=3.0.5 in /home/ianwoo/anaconda3/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.2 in /home/ianwoo/anaconda3/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.14.0 in /home/ianwoo/anaconda3/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): scikit-learn>=0.14.1 in /home/ianwoo/anaconda3/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.4.2 in /home/ianwoo/anaconda3/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): pandas in /home/ianwoo/anaconda3/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): senpy in /home/vlaand/.local/lib/python3.5/site-packages
Collecting pattern
  Using cached pattern-2.6.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3goxq977/pattern/setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3goxq977/pattern/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by drevicko** [comment]
Looks like this is an issue with `pattern` and python3.

Closing this issue...
